### ISSUE TITLE
random walk in debug mode

### ISSUE THREAD

**Issue by felix9** [tmedwards/sugarcube-2#188]
For a story I'm working on, I implemented a simple random-walk control in debug mode.
- Pressing the "walk" button (shortcut key <kbd>period</kbd>) will draw an outline on a random passage link. Pressing it again will visit that link.
- Pressing the "back" button (shortcut key <kbd>comma</kbd>) will do the reverse.

Does this seem like something that's generally useful? I've included the implementation below, and I'd be happy to make a PR to integrate it into Sugarcube-2 (and/or -3).

One subtlety of the implementation: It tries to do a shuffle, not uniform random, so in principle you could use walk/back to do a complete depth-first traversal of deterministic story graphs.

(This will probably need tweaking if the story has text inputs that expect to read comma or period.)

<details><summary>random-walk.css</summary>

```css
.random-walk {
  bottom: 100px;
  display: flex;
  flex-direction: column;
  font-size: 18px;
  gap: 8px;
  position: fixed;
  right: 4px;
}

.random-walk a {
  background-color: #eee;
  border: 1px solid transparent;
  border-radius: 4px;
  color: #000;
  cursor: pointer;
  opacity: 0.3;
  padding: 2px 4px;
}

.random-walk a:hover {
  background-color: #333;
  border-color: #eee;
  color: #eee;
}

.random-walk-chosen {
  outline: 1px solid #9cc;
}
```
</details>

<details><summary>random-walk.js</summary>

```js
/** Random walk */
function randomWalkSetup() {
  if (!Config.debug) return;

  const back = () => {
    const chosen = $('#passages .random-walk-chosen');
    if (chosen.length > 0) {
      chosen.removeClass('random-walk-chosen');
    } else {
      Engine.backward();
    }
  };

  const visited = new Set();
  const lastPick = {};
  const id = el => [$(el).attr('data-passage'), $(el).text()].join('|');
  const walk = () => {
    const chosen = $('#passages .random-walk-chosen');
    if (chosen.length === 1) {
      chosen.click();
      return;
    }
    chosen.removeClass('random-walk-chosen');

    const here = State.passage;
    const all = $('#passages a[data-passage]');
    if (all.length === 0) return;

    let avail = all.filter((i, el) => !visited.has(id(el)));
    if (avail.length === 0) {
      all.each((i, el) => visited.delete(id(el)));
      avail = all;
      if (avail.length !== 1) {
        avail = avail.filter((i, el) => id(el) !== lastPick[here]);
      }
    }

    const i = random(avail.length - 1);
    $(avail[i]).addClass('random-walk-chosen');
    avail[i].scrollIntoView();
    lastPick[here] = id(avail[i]);
    visited.add(lastPick[here]);
  };

  $(document).on(":passageend", () => {
    $(".random-walk").remove();
    const div = $("<div class=random-walk>").appendTo("#story");
    $('<a class=random-walk-back title="<comma> backward">back</a>')
      .on("click", back).appendTo(div);
    $('<a class=random-walk-go title="<period> forward">walk</a>')
      .on("click", walk).appendTo(div);
  });

  $(document).on("keydown", ev => {
    switch (ev.key) {
      case ",": back(); break;
      case ".": walk(); break;
    }
  });
}

randomWalkSetup();
```
</details>
